title = "MANIC | インディーゲームレビューサイト"
baseURL = "https://manic.fun/"
languageCode = "ja"
publishDir = "docs"
paginate = 10

[Params]
  description = "インディーゲームレビューサイト"
  image = "/image.png"

[permalinks]
  posts = "/:section/:slug/"

[taxonomies]
  tag = "tag"

[markup.goldmark.renderer]
  unsafe = true
